Elcodi\Component\Shipping\Entity\Abstracts\AbstractCarrierBaseRange:
    type: entity
    repositoryClass: Elcodi\Component\Shipping\Repository\CarrierBaseRangeRepository
    inheritanceType: joined
    table: carrier_base_range
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        carrier_price_range: Elcodi\Component\Shipping\Entity\CarrierPriceRange
        carrier_weight_range: Elcodi\Component\Shipping\Entity\CarrierWeightRange
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        description:
            column: description
            type: text
        priceAmount:
            column: price_amount
            type: integer
        enabled:
            column: enabled
            type: boolean
            nullable: false

    manyToOne:
        carrier:
            targetEntity: Elcodi\Component\Shipping\Entity\Interfaces\CarrierInterface
            inversedBy: ranges
            joinColumn:
                name: carrier_id
                referencedColumnName: id
                nullable: false
        fromZone:
            targetEntity: Elcodi\Component\Zone\Entity\Interfaces\ZoneInterface
            joinColumn:
                name: from_zone_code
                referencedColumnName: id
                nullable: false
        toZone:
            targetEntity: Elcodi\Component\Zone\Entity\Interfaces\ZoneInterface
            joinColumn:
                name: to_zone_code
                referencedColumnName: id
                nullable: false
        priceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: price_currency_iso
                referencedColumnName: iso
                nullable: false
