Elcodi\Component\Shipping\Entity\CarrierPriceRange:
    type: entity
    repositoryClass: Elcodi\Component\Shipping\Repository\CarrierPriceRangeRepository
    table: carrier_price_range

    fields:
        fromPriceAmount:
            column: from_price_amount
            type: integer
        toPriceAmount:
            column: to_price_amount
            type: integer

    manyToOne:
        fromPriceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: from_price_currency_iso
                referencedColumnName: iso
                nullable: true
        toPriceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                name: to_price_currency_iso
                referencedColumnName: iso
                nullable: false
