parameters:

    #
    # Entities
    #
    elcodi.entity.shipping_range.class: Elcodi\Component\Shipping\Entity\ShippingRange
    elcodi.entity.carrier.class: Elcodi\Component\Shipping\Entity\Carrier
    elcodi.entity.warehouse.class: Elcodi\Component\Shipping\Entity\Warehouse

    #
    # Factories
    #
    elcodi.factory.carrier.class: Elcodi\Component\Shipping\Factory\CarrierFactory
    elcodi.factory.shipping_range.class: Elcodi\Component\Shipping\Factory\ShippingRangeFactory
    elcodi.factory.warehouse.class: Elcodi\Component\Shipping\Factory\WarehouseFactory

    #
    # Providers
    #
    elcodi.provider.carrier.class: Elcodi\Component\Shipping\Provider\CarrierProvider
    elcodi.provider.shipping.class: Elcodi\Component\Shipping\Provider\ShippingProvider

    #
    # Resolvers
    #
    elcodi.resolver.shipping_range.class: Elcodi\Component\Shipping\Resolver\ShippingRangeResolver
