parameters:

    #
    # Entities
    #
    elcodi.entity.shipping_range.class: Elcodi\Component\Shipping\Entity\ShippingRange
    elcodi.entity.carrier.class: Elcodi\Component\Shipping\Entity\Carrier

    #
    # Factories
    #
    elcodi.factory.carrier.class: Elcodi\Component\Shipping\Factory\CarrierFactory
    elcodi.factory.shipping_range.class: Elcodi\Component\Shipping\Factory\ShippingRangeFactory

    #
    # Providers
    #
    elcodi.provider.shipping_range.class: Elcodi\Component\Shipping\Provider\ShippingRangeProvider

    #
    # Resolvers
    #
    elcodi.resolver.shipping_range.class: Elcodi\Component\Shipping\Resolver\ShippingRangeResolver

    #
    # Event Listeners
    #
    elcodi.event_listener.refresh_shipping_amount.class: Elcodi\Component\Shipping\EventListener\RefreshShippingAmountEventListener
