services:

    #
    # Factories
    #

    #
    # Factory for entity carrier
    #
    elcodi.factory.shipping_carrier:
        class: %elcodi.factory.shipping_carrier.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.shipping.entity.carrier.class%"]]

    #
    # Factory for entity carrier_price_range
    #
    elcodi.factory.shipping_carrier_price_range:
        class: %elcodi.factory.shipping_carrier_price_range.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.shipping.entity.carrier_price_range.class%"]]

    #
    # Factory for entity carrier_weight_range
    #
    elcodi.factory.shipping_carrier_weight_range:
        class: %elcodi.factory.shipping_carrier_weight_range.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.shipping.entity.carrier_weight_range.class%"]]

    #
    # Factory for entity carrier_weight_range
    #
    elcodi.factory.shipping_warehouse:
        class: %elcodi.factory.shipping_warehouse.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.shipping.entity.warehouse.class%"]]
