services:

    #
    # Object Managers
    #
    elcodi.object_manager.carrier_price_range:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier_price_range.class% ]

    elcodi.object_manager.carrier_weight_range:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier_weight_range.class% ]

    elcodi.object_manager.carrier:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier.class% ]

    elcodi.object_manager.warehouse:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.warehouse.class% ]
