services:

    #
    # Object Managers
    #
    elcodi.object_manager.shipping_carrier_price_range:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier_price_range.class% ]

    elcodi.object_manager.shipping_carrier_weight_range:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier_weight_range.class% ]

    elcodi.object_manager.shipping_carrier:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.carrier.class% ]

    elcodi.object_manager.shipping_warehouse:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.shipping.entity.warehouse.class% ]
