services:

    #
    # Providers
    #
    elcodi.provider.shipping_range:
        class: %elcodi.provider.shipping_range.class%
        arguments:
            - @elcodi.repository.carrier
            - @elcodi.converter.currency
            - @elcodi.matcher.zone
            - @elcodi.resolver.shipping_range
