services:

    #
    # Repositories
    #

    #
    # Repository for entity carrier_base_range
    #
    elcodi.repository.carrier_base_range:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_base_range.class%

    #
    # Repository for entity carrier_price_range
    #
    elcodi.repository.carrier_price_range:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_price_range.class%

    #
    # Repository for entity carrier_weight_range
    #
    elcodi.repository.carrier_weight_range:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_weight_range.class%

    #
    # Repository for entity carrier
    #
    elcodi.repository.carrier:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier.class%

    #
    # Repository for entity warehouse
    #
    elcodi.repository.warehouse:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.warehouse.class%
