services:

    #
    # Resolvers
    #
    elcodi.resolver.shipping_range:
        class: %elcodi.resolver.shipping_range.class%
        arguments:
            - @elcodi.converter.currency
            - %elcodi.resolver.carrier.strategy%
