services:

    #
    # Resolvers
    #
    elcodi.resolver.shipping_range:
        class: %elcodi.resolver.shipping_range.class%
        arguments:
            currency_converter: @elcodi.converter.currency
            carrier_resolver_strategy: %elcodi.resolver.carrier.strategy%
