services:

    #
    # Resolvers
    #
    elcodi.carrier_resolver:
        class: %elcodi.carrier_resolver.class%
        arguments:
            currency_converter: @elcodi.converter.currency
            carrier_resolver_strategy: %elcodi.core.shipping.carrier_resolver_strategy%
